name: Build WAR Package

on:
  workflow_dispatch:  # Allows manual triggering

  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]

env:
  GITLAB_PAT: ${{ secrets.GITLAB_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: user-profile-app
      
      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@v3.2.0
        id: Xygeni-Scanner
        with:
          xygeni_url: https://api.xygeni.io
          token: ${{ secrets.XYGENI_TOKEN }}
          gh_token: ${{ secrets.PAT_FOR_XYGENI_SCAN }}
          # Block Secrets => BREAK BUILD
          # command: -cop commitResolution:auto scan --fail-on file:/home/runner/work/DemoBH/DemoBH/guardrails/secrets-critical.guardrail --skip=codetamper,compliance --send-to github/status
          # Block Malware => BREAK BUILD
          command: -cop commitResolution:auto scan --fail-on="#no-secrets"  file:/home/runner/work/DemoBH/DemoBH/guardrails/malicious-deps.guardrail --skip=codetamper,compliance --send-to github/status
          # Only Scan
          # command: -cop commitResolution:auto scan --send-to github/status --never-fail

      - name: Archive WAR file
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: war-artifact
          path: user-profile-app/target/*.war
