name: Revoke valid secrets

on:
  workflow_dispatch:  # On-demand manual triggering

env:
  GITLAB_PAT: ${{ secrets.GITLAB_PAT }}

jobs:
  remediate-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@v3.2.0
        id: Xygeni-Scanner
        with:
          xygeni_url: https://api.xygeni.io
          token: ${{ secrets.XYGENI_TOKEN }}
          gh_token: ${{ secrets.PAT_FOR_XYGENI_SCAN }}
          command: -cop commitResolution:auto scan --run=secrets --auto-remediate --no-upload --never-fail

